services:
  postgres:
    image: postgres:16.2
    container_name: aegis-postgres
    environment:
      POSTGRES_DB: aegis_db
      POSTGRES_USER: aegis_user
      POSTGRES_PASSWORD: aegis_password
    ports:
      - "5432:5432"
    volumes:
      - aegis-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis_user -d aegis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: aegis-redis
    ports:
      - "6379:6379"
    volumes:
      - aegis-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: aegis-kafka
    ports:
      - "9092:9092"
    volumes:
      - aegis-kafka-data:/var/lib/kafka/data

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: aegis-zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:latest
    container_name: aegis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: aegis-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  aegis-postgres-data:
  aegis-redis-data:
  aegis-kafka-data: